"""your_message

Revision ID: 816f69038051
Revises: 27a10c458b6f
Create Date: 2023-11-01 13:56:26.860743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816f69038051'
down_revision: Union[str, None] = '27a10c458b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('cryptocurrency', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'cryptocurrency')
    # ### end Alembic commands ###
