"""initial migration

Revision ID: abd89a4fd82b
Revises: 
Create Date: 2023-10-30 19:48:24.481416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd89a4fd82b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cryptocurrency', sa.String(length=10), nullable=False),
    sa.Column('exchange_currency', sa.String(length=10), nullable=False),
    sa.Column('base_value', sa.Float(), nullable=False),
    sa.Column('trigger_value', sa.Float(), nullable=False),
    sa.Column('trigger_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    # ### end Alembic commands ###
